#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_PARALLEL=0
. ../../../testdata_tools/gen.sh

SMALLN=500
MEDN=5000
MAXN=100000

SMALLM=250
MEDM=5000
MAXM=100000

MAXQ=100000

use_solution arnar_100.py

compile random_generator.py

samplegroup
sample 1

group GA 10
tc GA-01 random_generator $SMALLN $SMALLN $MAXM $MAXM $MAXQ $MAXQ $MAXQ any
tc GA-02 random_generator $SMALLN $SMALLN $MAXM $MAXM $MAXQ $MAXQ $MAXQ move_much_left
tc GA-03 random_generator $SMALLN $SMALLN $MAXM $MAXM $MAXQ $MAXQ $MAXQ move_much_right
for i in {04..06}; do
tc GA-$i random_generator 2 $SMALLN 1 $MAXQ 1 $MAXQ $MAXQ any
done;

group GB 20
tc GB-01 random_generator $MAXN $MAXN $SMALLM $SMALLM $MAXQ $MAXQ $MAXQ any
tc GB-02 random_generator $MAXN $MAXN $SMALLM $SMALLM $MAXQ $MAXQ $MAXQ move_much_left
tc GB-03 random_generator $MAXN $MAXN $SMALLM $SMALLM $MAXQ $MAXQ $MAXQ move_much_right
for i in {04..06}; do
tc GB-$i random_generator 2 $MAXN 1 $SMALLN 1 $MAXQ $MAXQ any
done;

group GC 20
tc GC-01 random_generator $MEDN $MEDN $MEDM $MEDM $MAXQ $MAXQ $MAXQ any
tc GC-02 random_generator $MEDN $MEDN $MEDM $MEDM $MAXQ $MAXQ $MAXQ move_much_left
tc GC-03 random_generator $MEDN $MEDN $MEDM $MEDM $MAXQ $MAXQ $MAXQ move_much_right
for i in {04..06}; do
tc GC-$i random_generator 2 $MEDN 1 $MEDN 1 $MAXQ $MAXQ any
done;

group GD 20
tc GD-01 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ 1 any
tc GD-02 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ 1 move_much_left
tc GD-03 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ 1 move_much_right
for i in {04..06}; do
tc GD-$i random_generator 2 $MAXN 1 $MAXM 1 $MAXQ 1 any
done;

group GE 30
include_group GA
include_group GB
include_group GC
include_group GD
tc GE-01 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ $MAXQ any
tc GE-02 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ $MAXQ move_much_left
tc GE-03 random_generator $MAXN $MAXN $MAXM $MAXM $MAXQ $MAXQ $MAXQ move_much_right
for i in {04..06}; do
tc GE-$i random_generator 2 $MAXN 1 $MAXM 1 $MAXQ $MAXQ any
done;
