#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_PARALLEL=0
. ../../../testdata_tools/gen.sh

use_solution arnar_100.py

compile random_generator.py

samplegroup
sample 1

group GA 10
for i in {01..05}; do
tc GA-$i random_generator 1 500 1 100000 1 100000
done;

group GB 10
for i in {01..05}; do
tc GB-$i random_generator 1 100000 1 500 100000 100000
done;

#group GC 10
#for i in {01..40}; do
#tc GA-$i random_generator 1 500 1 500 1 500
#done;

group GD 10
for i in {01..05}; do
tc GD-$i random_generator 1 100000 1 100000 1 100000
done;
