#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../testdata_tools/gen.sh

use_solution arnar_fast_fif_100.java

compile random_generator.py
compile specific_generator.py

samplegroup
sample 1

group GA 10
tc GA-01 random_generator 500 500 10 10 1 1
for i in {02..04}; do
tc GA-$i random_generator 1 500 1 10 1 1
done;

group GB 15
include_group GA
tc GB-01 random_generator 500 500 10 10 2 2
for i in {02..05}; do
tc GB-$i random_generator 1 500 1 10 2 2
done;

group GC 20
include_group GB
tc GC-01 random_generator 500 500 10 10 5 5
tc GC-spec-01 specific_generator 500 5
tc GC-spec-02 specific_generator 500 2
for i in {02..05}; do
tc GC-$i random_generator 1 500 1 10 1 5
done;

group GD 10
include_group GC
tc GD-01 random_generator 1000 1000 100 100 100 100
for i in {02..10}; do
tc GD-$i random_generator 1 1000 1 100 1 100
done;

group GE 15
include_group GD
tc GE-01 random_generator 3*10**5 3*10**5 100 100 100 100
tc GE-spec-01 specific_generator 3*10**5 100
tc GE-spec-02 specific_generator 3*10**5 5
for i in {02..04}; do
tc GE-$i random_generator 1 3*10**5 1 100 1 100
done;

group GF 30
include_group GE
tc GF-01 random_generator 3*10**5 3*10**5 3*10**5 3*10**5 3*10**5 3*10**5
tc GF-spec-01 specific_generator 3*10**5 10000
for i in {02..04}; do
tc GF-$i random_generator 1 3*10**5 1 3*10**5 1 3*10**5
done;
