#!/bin/bash

RESULT=0
git diff-index --cached --name-only HEAD | grep "^problems" | cut -f2 -d'/' | uniq >> CHANGED_PROBLEMS
if ! ./scripts/check_all.sh . NO ; then
    RESULT=1
fi
rm CHANGED_PROBLEMS
exit $RESULT
